services:
  - type: web
    name: shortify
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn videoshorts.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-p)^!jd4n$7h_942*w!euvl+**@h-o*^o)n_es%+dw8jufg#nn*
      - key: DJANGO_SETTINGS_MODULE
        value: videoshorts.settings
